### ISSUE TITLE
Google.com doesn't have any fingerprints?

### ISSUE THREAD

**Issue by oroscobob** [abrahamjuliot/ublock-origin_abort_browser_fingerprinting#5]
Google.com doesn't have any fingerprints? Or is this code not fully working?

**Comment by abrahamjuliot** [comment]
Initially, this detected fingerprinting on google.com, but I adjusted the [ranking](https://github.com/abrahamjuliot/ublock-origin-abf/blob/d9b431e3e4ce69930f69fe3d1426975687c479b5/abf.js#L357)

As far as I know, google.com is only performing feature detection on the `screen` and `navigator` APIs (and from various scripts), and there's also a legitimate use of the Canvas API to render images. All that could technically be used to create a fingerprint, but the JS reads are not centralized to one file and there are no reads of Timezone, WebGL, or Media Devices, so I am hesitant to conclude google.com is fingerprinting. I'm certain there's a level of session tracking going on with ads, cookies, storage, etc., but it's not high entropy fingerprinting similar to [fingerprintjs](https://github.com/fingerprintjs/fingerprintjs/tree/master/src/sources).

**Comment by oroscobob** [comment]
Thank you for this script.
